name: sister-pore-c_base
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  # name: assign_pairs
  - python==3.9
  - pandas
  - pyarrow
  - pairtools==1.0.2
  # name: bcf_tools
  - bcftools==1.9
  - tabix==0.2.6
  # name: cooler
  - cooler==0.9.2
  # name: pairix
  - pairix
  # name: pairtools
  # - pairtools==0.3.0
  - coreutils
  # - tabix
  #name: whatshap
  - whatshap ==1.0
  # name: pore_c.yml
  - pore-c==0.4.0
  - aws-sdk-cpp==1.8.186
  # name: qc.yml (+pore_c.yml)
  - pandas
  - matplotlib
  - seaborn
  # name: bwa.yml
  - bwa
  - samtools
  - pysam
  - dask
  - pip
  - pip:
    - git+https://github.com/gerlichlab/spoc